### ISSUE TITLE
Add and Adjust Jump Settings

### ISSUE THREAD

**Issue by B-Swayze** [jamesmitchellwest/Astoria-Legend-Game#11]
1.) Create 2 more variations of jump height based on key hold length - tap=default height, medium hold=medium jump, long hold=max jump.

2.) Adjust jump boost tile settings.

- Standing idle on tile=default jump height
- Create 3 variations of jump height based on key hold length for boosted jump
- *MAYBE create an argument that progressively increases jump height slightly with consecutive jump boost tile collisions (max out after 3 jumps, but this sounds hard.)

**Comment by jamesmitchellwest** [comment]
@jwest6  I removed the extra lines on the player so now he just has the 1 rectangle hitbox.  I also overwrite the boostEntity rectangle drawn in Tiled and replace it with a line on each side of the entity.  This should hopefully make it easier detecting which side of the boostEnitity the player collides with.

ac06ffa

I also updated the map to give a better test area for the up boosts

![image](https://user-images.githubusercontent.com/20312086/116827935-60d9dc80-ab61-11eb-90dc-6211d3cfcb9c.png)
