### ISSUE TITLE
Health, Death, Lives, Game Over, Continue etc

### ISSUE THREAD

**Issue by jamesmitchellwest** [jamesmitchellwest/Astoria-Legend-Game#14]
How are we going to implement health? @B-Swayze are we going to use the zelda style hearts you had in the teaser video?

Should we have health re-charge collectables?

How do we want to animate dying?

Do we want to have lives and game over?

**Comment by B-Swayze** [comment]
@jamesmitchellwest Honestly I was picturing more of a time trial type gameplay with knock-backs being the only real consequence of enemy collision. Collectibles would act as score multipliers and collected throughout the world or by killing enemies.  Power ups affect attributes like speed, jump, attack, etc...

We could award stars at the end of each map based on time thresholds, and have a leaderboard scroll on the start menu.

Life based gameplay could be cool if we decide to make a co-op multiplayer option.  

Not saying that's what it has to be, just what I had in my head.
