### ISSUE TITLE
Create monster Gremlin

### ISSUE THREAD

**Issue by jamesmitchellwest** [jamesmitchellwest/Astoria-Legend-Game#3]
![Villian_Gremlin_120w](https://user-images.githubusercontent.com/20312086/116769609-f7dc5280-aa02-11eb-840b-d81f345b2c63.png)

![Projectile_Cassettes_24w](https://user-images.githubusercontent.com/20312086/116769665-54d80880-aa03-11eb-8376-b6670127638c.png)

Add cassette projectile.  Behavior undetermined at the moment.

Frame Width = 120pix

Jump sequence by Frames = 1, 2, 3, 4, 5, 4, 5, 4, 3, 1

**Comment by B-Swayze** [comment]
My thinking was that 3 cassettes would arc out of the boombox on frame count 3, 6, & 9 of the jump sequence. Trajectories would be semi-random, and cassette would spin on center axis.  Cassettes should not collide with platforms, only entity.
