### ISSUE TITLE
Add a knockback and switch to hurt frame while player is blinking

### ISSUE THREAD

**Issue by jamesmitchellwest** [jamesmitchellwest/Astoria-Legend-Game#7]

**Comment by B-Swayze** [comment]
Hold knockback until entity comes to a complete stop. 

*this might be a bug waiting to happen if the entity never comes to a stop, but I'm planning to utilize boost tiles to create a checkpoint style of progression, so if you were to get knocked down to the boost tiles they would carry you to a previously visited part of the map without having to create respawn points.
