### ISSUE TITLE
Bug: player speeds up when it should be slow

### ISSUE THREAD

**Issue by jamesmitchellwest** [jamesmitchellwest/Astoria-Legend-Game#8]
If player is running against the current on a horizontal speed boost he should be running slow.  If the player jumps toward the slowed direction and faces the boosted direction mid-air he will be boosted when he shouldn't be

**Comment by B-Swayze** [comment]
- player jumping against current should gain a small amount of speed when airborne 
- player velocity should reset to default when changing direction in air (similar to what you said above but its doing the same thing when travelling with the current)
- fix bug causing player to stop on boost arrows when holding crouch+direction.
- fix bug causing player to move slower on boost arrows if facing left vs facing right
- Add slide/friction to character movement so when exiting boost arrows there is a natural transition from fast to default speed
